Homework05
AlexandraLeonova/cs102 pull request #19
Opened 2021-01-06 23:09 UTC by AlexandraLeonova

2021-01-08 19:34 UTC, AlexandraLeonova commented
@anastasiiaCher , я уже 2 дня сижу с одной и той же проблемой в юниттестах. похожая ошибка была решена дополнением файла cs102.yml(обсуждения в дискорде). у меня же ничего не изменилось. может ли быть так, что опять проблема в макбуке?  
<img width="1440" alt="Снимок экрана 2021-01-08 в 22 33 57" src="https://user-images.githubusercontent.com/70950413/104056479-9ac55280-5201-11eb-83b8-1c42fe35ebff.png">

2021-01-09 21:14 UTC, AlexandraLeonova commented
@anastasiiaCher, перепробовала все, ошибка не исправляется. подскажите, пожалуйста, в чем проблема

2021-01-11 17:29 UTC, AlexandraLeonova commented
@anastasiiaCher мне нужен ваш совет

2021-01-13 18:09 UTC, AlexandraLeonova commented
@anastasiiaCher !!

2021-01-14 23:36 UTC, AlexandraLeonova commented
@anastasiiaCher у меня горят баллы

2021-01-14 23:36 UTC, AlexandraLeonova commented
Очень жду вашей проверки

2021-01-20 16:33 UTC, AlexandraLeonova commented
@anastasiiaCher , одобрите, пожалуйста

2021-01-24 10:52 UTC, anastasiiaCher requested changes
Несколько моментов надо поправить, чтобы корректно работало не только на юниттестах, но и на реальных данных ВК,

2021-01-24 10:52 UTC, anastasiiaCher commented on homework05/research/network.py
> +
Потеряли импорт библиотеки `community`. Было так: `import community as community_louvain`

2021-01-24 10:52 UTC, anastasiiaCher commented on homework05/research/network.py
> +        get_friends(user_id).items  # type: ignore
Результат работы функции `get_friends()` здесь надо присваивать `friends`. Иначе зачем было делать проверку на непустоту? Неприсвоенное значение уходит в никуда.

2021-01-24 10:52 UTC, anastasiiaCher commented on homework05/vkapi/friends.py
> +                "target_uids": target_uids[shift : shift + 100],  # type: ignore
Если у юзера меньше 100 друзей, то общие друзья будут найдены только для первого юзера в списке. Подумайте, как это исправить, т.к. это кардинально влияет на построение графа.

2021-01-24 10:52 UTC, anastasiiaCher commented on homework05/research/age.py
> +    if ages == []:
`if not ages`

2021-01-24 13:15 UTC, AlexandraLeonova commented
@anastasiiaCher ошибки исправила

2021-01-24 14:16 UTC, anastasiiaCher approved these changes
Теперь ок. На 11.01 получается 12 баллов.

2021-01-24 16:00 UTC, merged