Homework01
AlexandraLeonova/cs102 pull request #4
Opened 2020-11-03 09:02 UTC by AlexandraLeonova

2020-11-03 17:47 UTC, anastasiiaCher requested changes
В Виженере все еще не работает `decrypt_vigenere()`. В RSA все еще не проходит один юнит-тест. Очень жду доработок.

2020-11-03 17:47 UTC, anastasiiaCher commented on homework01/caesar.py
> +            plaintext += chr(((ord(ciphertext[s]) - ord('A') - shift) % 26) + ord('A')
В 44 строке забыли в конце закрывающую скобку. И поправьте чуть-чуть отступы.

2020-11-06 14:24 UTC, AlexandraLeonova commented
посмотрите, пожалуйста,@anastasiiaCher

2020-11-06 16:56 UTC, anastasiiaCher requested changes
Цезарь: все ок.
Виженер: тесты все еще не проходят на декрипте, когда текст написан маленькими буквами.
RSA: не проходит юнит-тест, т.к. у вас `generate_keypair()` взята из старого шаблона. Скопируйте из нового и все получится.

2020-11-07 11:22 UTC, anastasiiaCher requested changes
RSA теперь работает. Сделайте его чуть лучше, внеся одну правочку.
И жду Виженер.

2020-11-07 11:22 UTC, anastasiiaCher commented on homework01/rsa.py
>      if a == 0:
Строки 32-35, где `if`-`elif` можно свернуть в один `if` (через логический оператор `or`), т.к. вы в обоих случаях возвращаете `a + b`

2020-11-08 16:11 UTC, anastasiiaCher requested changes

2020-11-08 16:11 UTC, anastasiiaCher commented on homework01/vigenere.py
> +        elif ord("a") <= ord(keyword[t]) - ord("z"):
У вас ошибка в строке 54. Когда замените `-` на `<=` код заработает и пройдет все тесты.

2020-11-08 16:14 UTC, AlexandraLeonova commented on homework01/vigenere.py
> +        elif ord("a") <= ord(keyword[t]) - ord("z"):
спасибо!

2020-11-08 16:15 UTC, AlexandraLeonova commented
из-за того, что создала экшнс в дз2, у меня теперь конфликт в cs102.yml в дз1

мне стоит просто переименовать файл? 
<img width="1440" alt="Снимок экрана 2020-11-08 в 19 15 32" src="https://user-images.githubusercontent.com/70950413/98470456-c7a3bc00-21f6-11eb-8313-2b0e2cf899ba.png">

2020-11-08 16:26 UTC, anastasiiaCher commented
Т.к. у вас теперь `.github/workflows/cs102.yml` есть в master, вам он в принципе больше не нужен в ветке homework01

2020-11-08 16:29 UTC, AlexandraLeonova commented
значит, могу прям в vs удалить?
<img width="1440" alt="Снимок экрана 2020-11-08 в 19 28 21" src="https://user-images.githubusercontent.com/70950413/98470721-aba11a00-21f8-11eb-8775-76c972087bfe.png">

2020-11-08 17:52 UTC, AlexandraLeonova commented
все сделала, теперь и на дз1 галочка @anastasiiaCher

2020-11-08 18:26 UTC, anastasiiaCher approved these changes
Все, первая работа сдана.

2020-11-09 06:45 UTC, merged