Homework02
AlexandraLeonova/cs102 pull request #6
Opened 2020-11-08 16:25 UTC by AlexandraLeonova

можете теперь проверить. 
извините

2020-11-08 18:31 UTC, anastasiiaCher requested changes
Реализацию функции `get_col()` тоже можно свернуть в списковое включение и сразу отправить в `return`. В остальном все ок.

2020-11-09 08:41 UTC, AlexandraLeonova commented
теперь выдает ошибку(((
<img width="1440" alt="Снимок экрана 2020-11-09 в 11 41 01" src="https://user-images.githubusercontent.com/70950413/98518440-73ddb500-2280-11eb-8849-c061339a964f.png">

2020-11-09 08:41 UTC, AlexandraLeonova commented
@anastasiiaCher

2020-11-09 14:55 UTC, anastasiiaCher commented
Между функциями должно быть ровно две пустых строки. У вас сейчас одна. Об этом и говорит black. Также обратите внимание, что вы в принципе можете не вводить переменную `col`. Можно сразу же списковое включение записать в `return`, как у вас сделано в других функциях.

2020-11-09 14:58 UTC, anastasiiaCher commented
Чтобы не возникало проблем с black на гитхабе, вы можете проверять форматирование до загрузки.
1. Воспользуйтесь black для форматирования (удачнее всего форматируется с длиной строки 90: `black -l 90 sudoku.py`)
2. Сделайте проверку форматирования вот так: `black --check --diff --color sudoku.py`. Для этого у вас должна быть установлена версия black 20.8b1.

2020-11-09 16:13 UTC, AlexandraLeonova commented
все ок теперь. можно мерджить? @anastasiiaCher

2020-11-09 19:01 UTC, anastasiiaCher approved these changes
В принципе теперь все ок, да. Только не забудьте сделать репозиторий private.

2020-11-10 08:13 UTC, merged